[alias]

[settings]
experimental = true
vfox = false

[settings.pipx]
uvx = true

[settings.npm]
bun = true

[tools]
"pipx:llm" = "latest"
"pipx:xxh-xxh" = "latest"
"pipx:shell-gpt" = "latest"
"pipx:ipython" = "latest"
"pipx:epy-reader" = "latest"
"pipx:aider-chat" = { version = "latest", extras = "browser,playwright,fzf,help" }
zig = "0.13.0"
lazydocker = "0.23"
node = "23"
python = "3.12"
uv = "latest"
"ubi:duckdb/duckdb" = "latest"
bun = "latest"
"cargo:bottom" = "latest"
"cargo:probe-rs-tools" = "latest"
"cargo:eza" = "latest"
"cargo:zellij" = "latest"
"cargo:jaq" = "latest"
"cargo:jnv" = "latest"
"cargo:ttyper" = "latest"
"pipx:playwright" = "latest"
"pipx:posting" = "latest"
"cargo:rainfrog" = "latest"
"ubi:jesseduffield/lazydocker" = "latest"
"npm:eslint" = "latest"
"cargo:monolith" = "latest"
"cargo:jj-cli" = "latest"
"cargo:lazyjj" = "latest"
"cargo:scooter" = "latest"
"cargo:tmux-rs" = "latest"
"cargo:gittype" = "latest"
