[alias]

[settings]
experimental = true
vfox = false

[settings.pipx]
uvx = true

[settings.npm]
bun = true

[tools]
"pipx:llm" = "latest"
"pipx:xxh-xxh" = "latest"
"pipx:epy-reader" = "latest"
erlang = "28.3"
elixir = "1.19.4-otp-28"
ruby = "4.0"
zig = "0.15.2"
gleam = "1.14.0"
lazydocker = "0.24"
"ubi:duckdb/duckdb" = "latest"
"cargo:bottom" = "latest"
"cargo:probe-rs-tools" = "latest"
"cargo:zellij" = "latest"
"cargo:jaq" = "latest"
"cargo:jnv" = "latest"
"cargo:ttyper" = "latest"
"pipx:playwright" = "latest"
"pipx:posting" = "latest"
"cargo:rainfrog" = "latest"
"ubi:jesseduffield/lazydocker" = "latest"
"cargo:monolith" = "latest"
"cargo:jj-cli" = "latest"
"cargo:lazyjj" = "latest"
"cargo:scooter" = "latest"
"cargo:gittype" = "latest"
"cargo:xleak" = "latest"
"pipx:aider-chat" = { version = "latest", playwright = "", browser = "", uvx_args = "--python 3.12" }
